<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="home-PC" name="org.acc.Testng.A" tests="11" failures="0" timestamp="09 Apr 2020 07:08:35 GMT" time="0.052" errors="1">
  <testcase name="test2" time="0.004" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.acc.Testng.A.test2(A.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.005" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.022" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
</testsuite> <!-- org.acc.Testng.A -->
